baseURL = "https://nagatani.github.io/"
languageCode = "ja-jp"
title = "Memorandum"
theme = "hucore"

hasCJKLanguage = true
publishDir = "public"

copyright = "&copy; 2018 | Follow on <a href=\"https://twitter.com/Nagatani\" target=\"_blank\">Twitter</a>"
disqusShortname = "nagatanigithubio"
googleAnalytics = "UA-43292130-3"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "メモにメモ以上の価値を求めるのはいけない"
keywords = []
author = "Nagatani"
sharingicons = false
DateForm = "2006-01-02 Monday"

[params.highlight]
style = "monokai"
languages = []

[[params.social]]
url = "https://github.com/Nagatani"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/Nagatani"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
