baseURL = "https://nagatani.github.io/"
languageCode = "ja-jp"
title = "Memorandum"
theme = "Memorandum"

hasCJKLanguage = true
publishDir = "public"

copyright = "&copy; 2018 <a href=\"https://nagatani.me/\" target=\"_blank\">Nagatani</a>"
disqusShortname = "nagatanigithubio"
googleAnalytics = "UA-43292130-3"
summarylength = 200

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "メモにメモ以上の価値を求めるのはいけない"
keywords = []
author = "Nagatani"
profile = "世知辛い世の中を静かに暮らしたい<br><a href=\"https://nagatani.me/\" target=\"_blank\">https://nagatani.me/</a>"
displayauthor = false
DateForm = "2006-01-02"

[params.highlight]
theme = "monokai-sublime"

[[params.social]]
url = "https://github.com/Nagatani"
fa_icon_class = "fab fa-github"

[[params.social]]
url = "https://twitter.com/Nagatani"
fa_icon_class = "fab fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon_class = "fas fa-rss"
